import { NextResponse } from 'next/server';

import { buildFixPack, punchListMarkdown } from '@botready/core';

import { currentUser, hasFixpackEntitlement } from '@/lib/auth';
import { loadScanView } from '@/lib/scan-data';
import { zip } from '@/lib/zip';

export const runtime = 'nodejs';
export const dynamic = 'force-dynamic';

/**
 * GET /api/fixpack/:scanId -> a zip
 *
 * The entitlement unlocks the download. The files are generated on the way out
 * from the evidence rows rather than stored, because they are a pure function
 * of the scan and storing them would only create a second thing that could go
 * stale.
 *
 * Every response here is a plain sentence about what to do next. A 401 from a
 * download link with a JSON blob behind it is a dead end.
 */
export async function GET(_request: Request, context: { params: Promise<{ scanId: string }> }) {
  const { scanId } = await context.params;

  const user = await currentUser();
  if (!user) {
    return NextResponse.redirect(
      new URL(`/sign-in?next=${encodeURIComponent(`/api/fixpack/${scanId}`)}`, _request.url),
      { status: 303 },
    );
  }

  if (!(await hasFixpackEntitlement(user.id))) {
    return text(
      403,
      `${user.email} has not bought the fix pack. If you have, and the receipt went to a different address, sign in with that one. The result page has the button.`,
    );
  }

  const view = await loadScanView(scanId);
  if (!view) return text(404, 'No scan with that id.');
  if (!view.score) {
    return text(409, 'This scan did not produce a result, so there is nothing to generate from it.');
  }

  const pack = buildFixPack(view.site.domain, view.results);
  const generatedAt = new Date(view.scan.finished_at ?? view.scan.created_at);

  const readme = [
    `# Fix pack for ${pack.domain}`,
    '',
    `Generated by botready.dev from scan ${scanId}, checked ${generatedAt.toISOString()}.`,
    `Scanner ${view.scan.scanner_version ?? 'unrecorded'}, scoring v${view.score.scoringVersion}.`,
    '',
    'Every value in these files came out of that scan. Nothing was guessed; where',
    'the scan could not read a fact, the file says so in a comment or an <angle>',
    'placeholder rather than filling in something plausible.',
    '',
    '## Files',
    '',
    ...pack.files.map((f) => `- \`${f.name}\` — ${f.purpose}${f.incomplete ? ' (incomplete: see the note inside)' : ''}`),
    '- `punch-list.md` — what to do, ordered by effort rather than by points.',
    '',
    'Re-run the check after each change rather than after all of them.',
    `https://botready.dev/scan/${scanId}`,
    '',
  ].join('\n');

  const archive = zip([
    { name: 'README.md', content: readme, modified: generatedAt },
    ...pack.files.map((f) => ({ name: f.name, content: f.content, modified: generatedAt })),
    {
      name: 'punch-list.md',
      content: punchListMarkdown(pack.domain, pack.punchList),
      modified: generatedAt,
    },
  ]);

  return new Response(Buffer.from(archive), {
    status: 200,
    headers: {
      'content-type': 'application/zip',
      'content-disposition': `attachment; filename="botready-fixpack-${pack.domain}.zip"`,
      'content-length': String(archive.byteLength),
      'cache-control': 'private, no-store',
    },
  });
}

function text(status: number, body: string): Response {
  return new Response(body + '\n', {
    status,
    headers: { 'content-type': 'text/plain; charset=utf-8', 'cache-control': 'no-store' },
  });
}
