/**
 * The fix pack, assembled once.
 *
 * The download route and the purchase email both hand over the same archive,
 * and they used to build it from two copies of the same twenty lines. One copy
 * is enough: a buyer who downloads the pack and a buyer who opens the
 * attachment should not be able to get different files.
 */

import { buildFixPack, punchListMarkdown } from '@botready/core';

import type { ScanView } from './scan-data';

import { zip } from './zip';
import { SITE } from './site';

export interface AssembledPack {
  domain: string;
  filename: string;
  /** The zip, as bytes. */
  archive: Uint8Array;
  /** What is inside it, for an email that wants to list the contents. */
  names: string[];
}

export function assembleFixPack(view: ScanView, scanId: string): AssembledPack | null {
  if (!view.score) return null;

  const pack = buildFixPack(view.site.domain, view.results);
  const generatedAt = new Date(view.scan.finished_at ?? view.scan.created_at);

  const readme = [
    `# Fix pack for ${pack.domain}`,
    '',
    `Generated by ${SITE.name} from scan ${scanId}, checked ${generatedAt.toISOString()}.`,
    `Scanner ${view.scan.scanner_version ?? 'unrecorded'}, scoring v${view.score.scoringVersion}.`,
    '',
    'Every value in these files came out of that scan. Nothing was guessed; where',
    'the scan could not read a fact, the file says so in a comment or an <angle>',
    'placeholder rather than filling in something plausible.',
    '',
    '## Files',
    '',
    ...pack.files.map((f) => `- \`${f.name}\` — ${f.purpose}${f.incomplete ? ' (incomplete: see the note inside)' : ''}`),
    '- `punch-list.md` — what to do, ordered by effort rather than by points.',
    '- `botready-fixes.md` — a full prompt for your coding agent. Paste it into Claude Code or Cursor.',
    '',
    'Re-run the check after each change rather than after all of them.',
    `${SITE.origin}/scan/${scanId}`,
    '',
  ].join('\n');

  const entries = [
    { name: 'README.md', content: readme, modified: generatedAt },
    ...pack.files.map((f) => ({ name: f.name, content: f.content, modified: generatedAt })),
    { name: 'punch-list.md', content: punchListMarkdown(pack.domain, pack.punchList), modified: generatedAt },
    { name: 'botready-fixes.md', content: pack.agentPrompt, modified: generatedAt },
  ];

  return {
    domain: pack.domain,
    filename: `botready-fixpack-${pack.domain}.zip`,
    archive: zip(entries),
    names: entries.map((e) => e.name),
  };
}
