#!/usr/bin/env node
/**
 * Every copy of the mark, from the one drawing.
 *
 *   pnpm icons
 *
 * The drawing lives in `apps/web/lib/logo.ts` and nowhere else. This writes
 * the SVGs from it and then the rasters from those. Before, the paths were
 * carried separately by the Mark component, app/icon.svg, public/logo.svg,
 * public/bimi.svg and assets/icon/apple-icon.svg, each with a comment asking
 * whoever edited one to remember the others — which is the comment you write
 * when the build should have been doing it.
 *
 * `apps/web/app/icon.svg` is shipped as-is as well as derived from — a browser
 * that takes an SVG favicon gets the vector:
 *
 *   app/favicon.ico     16, 32 and 48, for the browsers and crawlers that ask
 *                       for /favicon.ico by name
 *   app/apple-icon.png  180x180, from assets/icon/apple-icon.svg, which is the
 *                       same mark without the rounded tile or the ink border:
 *                       iOS applies its own mask, and a rounded rectangle
 *                       inside a rounded mask reads as a sticker of an icon
 *   public/logo.svg     the logo the JSON-LD and the agent manifests point at.
 *                       Not public/icon.svg: app/icon.svg already claims that
 *                       URL through Next's own convention, and two files
 *                       answering to one path is a trap for whoever edits one
 *   public/bimi.svg     the same mark in SVG Tiny PS, which is the profile
 *                       BIMI requires of a logo shown beside an email
 *
 * Run this after editing lib/logo.ts. The outputs are committed, so a build
 * never needs a browser.
 */

import { copyFileSync, mkdirSync, readFileSync, writeFileSync } from 'node:fs';
import { dirname, join } from 'node:path';
import { fileURLToPath, pathToFileURL } from 'node:url';

const ROOT = join(dirname(fileURLToPath(import.meta.url)), '..');
const APP = join(ROOT, 'apps/web/app');
const SOURCE = join(ROOT, 'apps/web/assets/icon');

const { chromium } = await import('playwright').catch(() =>
  import(pathToFileURL(join(ROOT, 'tools/node_modules/playwright/index.mjs')).href),
);

// The drawing is TypeScript, so it is read as text rather than imported: this
// script runs under plain node with no build step. Both patterns fail loudly
// if lib/logo.ts stops exposing them as literals.
const logo = readFileSync(join(ROOT, 'apps/web/lib/logo.ts'), 'utf8');
const body = logo.match(/export const MARK_BODY = `([\s\S]*?)`;/)?.[1];
const viewBox = logo.match(/export const MARK_VIEWBOX = '([^']+)'/)?.[1];
if (!body || !viewBox) {
  throw new Error('apps/web/lib/logo.ts no longer exposes MARK_BODY and MARK_VIEWBOX as literals');
}

const GENERATED = [
  'Generated by scripts/build-icons.mjs from apps/web/lib/logo.ts.',
  'Do not edit this file: change the drawing there and run `pnpm icons`.',
];

function svgDoc({ size, root = '', notes = [] }) {
  const comment = `  <!--\n${[...GENERATED, ...notes].map((l) => `    ${l}`).join('\n')}\n  -->\n`;
  return (
    `<svg xmlns="http://www.w3.org/2000/svg"${root} viewBox="${viewBox}" width="${size}" height="${size}">\n` +
    `  <title>BotReady</title>\n${comment}  ${body}\n</svg>\n`
  );
}

const tile = svgDoc({ size: 512, notes: ["Next's icon convention needs a literal file at this path."] });
// iOS applies its own rounded mask, so the apple icon is the same mark with no
// tile of its own. The drawing has never had one, so the two are identical
// today and the file stays separate because that could change.
const apple = svgDoc({ size: 180 });

mkdirSync(SOURCE, { recursive: true });
writeFileSync(join(APP, 'icon.svg'), tile);
writeFileSync(join(SOURCE, 'apple-icon.svg'), apple);
writeFileSync(
  join(ROOT, 'apps/web/public/bimi.svg'),
  svgDoc({
    size: 512,
    root: ' version="1.2" baseProfile="tiny-ps"',
    notes: ['SVG Tiny PS, which is the profile BIMI requires.'],
  }),
);

const browser = await chromium.launch();
const page = await browser.newPage();

async function render(svg, size, path) {
  await page.setViewportSize({ width: size, height: size });
  await page.setContent(
    `<style>html,body{margin:0;padding:0}svg{display:block;width:${size}px;height:${size}px}</style>${svg}`,
  );
  await page.screenshot({ path, omitBackground: true });
}

await render(apple, 180, join(APP, 'apple-icon.png'));

// An ICO directory entry may carry PNG data rather than a BMP, which is how
// every icon since Vista has been packed and is why there is no BMP encoder
// in this file.
const SIZES = [16, 32, 48];
const pngs = [];
for (const size of SIZES) {
  const path = join(SOURCE, `.ico-${size}.png`);
  await render(tile, size, path);
  pngs.push(readFileSync(path));
}
await browser.close();

const header = Buffer.alloc(6);
header.writeUInt16LE(0, 0); // reserved
header.writeUInt16LE(1, 2); // 1 = icon, 2 = cursor
header.writeUInt16LE(SIZES.length, 4);

let offset = 6 + SIZES.length * 16;
const entries = SIZES.map((size, i) => {
  const entry = Buffer.alloc(16);
  entry.writeUInt8(size, 0); // 0 would mean 256
  entry.writeUInt8(size, 1);
  entry.writeUInt8(0, 2); // palette entries; 0 for truecolour
  entry.writeUInt8(0, 3); // reserved
  entry.writeUInt16LE(1, 4); // colour planes
  entry.writeUInt16LE(32, 6); // bits per pixel
  entry.writeUInt32LE(pngs[i].length, 8);
  entry.writeUInt32LE(offset, 12);
  offset += pngs[i].length;
  return entry;
});

writeFileSync(join(APP, 'favicon.ico'), Buffer.concat([header, ...entries, ...pngs]));

// The manifests and the JSON-LD want a logo URL they can state plainly, and
// Next serves the app convention as /icon.svg?<hash>. Same mark, own path.
copyFileSync(join(APP, 'icon.svg'), join(ROOT, 'apps/web/public/logo.svg'));

console.log(
  `icon.svg, apple-icon.svg, bimi.svg, logo.svg, apple-icon.png (180), favicon.ico (${SIZES.join(', ')})`,
);
