import type { FixFile, ScanFacts } from './index';
import { brandFrom } from './shared';

/**
 * corroboration.md — the half of the problem that is not on your server.
 *
 * The other files in this pack change what an assistant reads on your site. This
 * one is about whether anything anywhere agrees with it. Assistants weight
 * claims that more than one source makes, so a page saying you integrate with
 * GitHub counts for less on its own than the same fact appearing on your site,
 * your docs and a directory listing that names you the same way.
 *
 * Nothing here can be generated as a file, which is why it is a checklist
 * rather than a paste-in. It is the honest shape of the work: a page of things
 * to go and do, ordered by how much each one is worth against how long it
 * takes, with your own domain and brand filled in so none of it is generic.
 *
 * No claims are invented here either. Every line is an instruction to state
 * something true in one more place, never to say something new.
 */

interface Task {
  title: string;
  detail: string;
  effort: string;
}

export function buildCorroboration(domain: string, facts: ScanFacts): FixFile {
  const brand = brandFrom(facts.siteTitle, domain);
  const origin = `https://${domain}`;

  const tasks: Task[] = [
    {
      title: `Use one spelling of "${brand}" everywhere`,
      detail: `An assistant links mentions by name. "${brand}", "${brand} App" and "${brand.toLowerCase()}.io" read as up to three companies, and each one gets a third of the evidence. Pick the form on your own homepage title and make every profile match it exactly.`,
      effort: 'an hour',
    },
    {
      title: 'Add sameAs links to your Organization block',
      detail: `sameAs is how you tell a machine that the ${brand} on your site and the ${brand} on those profiles are one company. Add every profile you control — GitHub, LinkedIn, X, Crunchbase, your directory listings — as an array on the Organization node in jsonld.html.`,
      effort: 'an hour',
    },
    {
      title: 'Get the facts in fit.html onto one page a human wrote about you',
      detail: 'A directory entry, a comparison post, a review listing. Same price, same audience, same integrations, same words. Corroboration is not more marketing; it is the same fact in a second place.',
      effort: 'a few days, mostly waiting',
    },
    {
      title: 'Make your docs crawlable as their own pages',
      detail: `Docs behind a client-side router or a login are invisible, and docs are where every specific answer lives. Check ${origin}/docs returns real HTML to a plain fetch — the scan's own JS dependency figure on your result page tells you whether it does.`,
      effort: 'depends on your docs',
    },
    {
      title: 'Date your changelog',
      detail: 'Recency is a signal an assistant can check and most sites throw away. A changelog with real dates on real entries answers "is this maintained" without anybody having to ask you.',
      effort: 'twenty minutes',
    },
  ];

  const lines: string[] = [];
  lines.push(`# Getting corroborated — ${brand}`);
  lines.push('');
  lines.push('Generated by botready.dev. This file is a checklist, not something to paste.');
  lines.push('');
  lines.push('The other files in this pack change what an assistant reads on your own');
  lines.push('site. This one is about whether anything else agrees with it. A fact stated');
  lines.push('in one place is a claim; the same fact in three places is a fact, and');
  lines.push('assistants weight the difference.');
  lines.push('');
  lines.push('Nothing below asks you to say anything new. Every line is the same true');
  lines.push('thing, stated once more somewhere it will be found.');
  lines.push('');

  tasks.forEach((task, i) => {
    lines.push(`## ${i + 1}. ${task.title}`);
    lines.push('');
    lines.push(task.detail);
    lines.push('');
    lines.push(`Effort: ${task.effort}`);
    lines.push('');
  });

  lines.push('---');
  lines.push('');
  lines.push('## What this file will not tell you');
  lines.push('');
  lines.push('Which directories are worth being in for your sector, and who your');
  lines.push('assistants actually name today when asked about your category. Neither is');
  lines.push('visible from a scan of your own site — the first needs a human who knows');
  lines.push('your market, and the second needs somebody to go and ask the assistants.');
  lines.push('');
  lines.push(`We do the asking: botready.dev tracks named prompts against ${domain} and`);
  lines.push('records who gets named, so you can see whether any of this moved. That is a');
  lines.push('measurement over weeks rather than a file, which is why it is not in this');
  lines.push('zip.');

  return {
    name: 'corroboration.md',
    purpose: 'A checklist for the half of the problem that is not on your server: getting the same facts stated somewhere else.',
    language: 'markdown',
    content: lines.join('\n') + '\n',
    // Nothing in the catalog scores off-site corroboration yet, and claiming a
    // check this does not move would be the first dishonest number in the pack.
    addresses: [],
    incomplete: false,
  };
}
