import type { FixFile, ScanFacts } from './index';
import { brandFrom, pathOf } from './shared';

/**
 * fit.html — the facts a constraint query is made of.
 *
 * jsonld.html already says who you are and that you sell something. This says
 * the things an assistant has to compare: what it costs, per what, who it is
 * for, what it connects to, where it stops. A question like "a tracker for five
 * people under $10 a seat that works with GitHub" is three constraints, and a
 * site that states none of them as facts cannot be matched against any of them
 * however well it is written.
 *
 * Everything here is a placeholder except the brand, the URLs and whether a
 * pricing page exists, because those are the only relevant things a scan sees.
 * The value is not that we filled it in — it is that the shape is right, the
 * fields are the ones that decide recommendations, and each is wired to the
 * page it should be read from.
 *
 * additionalProperty carries the comparison axes. It is the least glamorous
 * part of schema.org and the part an assistant can actually line up side by
 * side against a competitor.
 */

/**
 * The axes a buyer constrains on, as PropertyValue rows.
 *
 * Deliberately short. A long list of properties nobody fills in is worse than
 * six that get filled, and these six are the ones that appear in the phrasing
 * of real questions: price, unit, free tier, team size, integrations, limits.
 */
const AXES: Array<{ name: string; placeholder: string; why: string }> = [
  { name: 'Starting price', placeholder: '<8>', why: 'the number in "under $10 a seat"' },
  { name: 'Price unit', placeholder: '<per seat per month>', why: 'what that number buys' },
  { name: 'Free tier', placeholder: '<free for up to 5 people, or "none">', why: 'the most asked filter there is' },
  { name: 'Built for', placeholder: '<product teams of 2 to 20>', why: 'the size constraint' },
  // Named vendors here would collide with the reader's own brand — a fixture
  // run produced "<GitHub, Slack, Linear>" on linear.app, telling Linear to
  // list itself as an integration. The instruction carries the shape instead.
  { name: 'Integrates with', placeholder: '<name each one; a list, not "your favourite tools">', why: 'named tools, not "your stack"' },
  { name: 'Not for', placeholder: '<enterprises needing SSO and audit logs>', why: 'ruling yourself out of the wrong questions is how you win the right ones' },
];

export function buildFit(domain: string, facts: ScanFacts): FixFile {
  const origin = `https://${domain}`;
  const brand = brandFrom(facts.siteTitle, domain);
  const pricingPage = facts.pages.find((p) => /^\/(pricing|plans|price)/i.test(pathOf(p.url)));
  const pricingUrl = pricingPage?.url ?? `${origin}/pricing`;

  const block = {
    '@context': 'https://schema.org',
    '@type': 'Product',
    '@id': `${origin}/#offering`,
    name: brand,
    brand: { '@id': `${origin}/#organization` },
    url: origin,
    audience: {
      '@type': 'Audience',
      audienceType: '<product teams of 2 to 20>',
    },
    offers: {
      '@type': 'Offer',
      url: pricingUrl,
      price: '<8.00>',
      priceCurrency: '<USD>',
      availability: 'https://schema.org/InStock',
      priceSpecification: {
        '@type': 'UnitPriceSpecification',
        price: '<8.00>',
        priceCurrency: '<USD>',
        unitText: '<per seat per month>',
      },
    },
    additionalProperty: AXES.map((axis) => ({
      '@type': 'PropertyValue',
      name: axis.name,
      value: axis.placeholder,
    })),
  };

  const lines: string[] = [];
  lines.push(`<!-- What ${brand} costs and who it is for — ${domain}`);
  lines.push('     Generated by botready.dev.');
  lines.push('');
  lines.push('     An assistant answering "a tracker for five people under $10 a seat"');
  lines.push('     is matching three constraints. It can only match a constraint that is');
  lines.push('     stated as a fact somewhere it can read. This is where you state them.');
  lines.push('');
  lines.push('     Every <angle bracket> is a fact this scan cannot see and will not');
  lines.push('     guess. The example values are shapes, not suggestions — replace them.');
  lines.push('');
  if (facts.offerNodes > 0) {
    lines.push(`     Your pages already carry ${facts.offerNodes} Offer node(s). Merge with those`);
    lines.push('     rather than adding a second price for the same thing.');
  } else {
    lines.push('     The scan found no Offer node on your pages, so nothing currently');
    lines.push('     states your price in a form a machine reads.');
  }
  lines.push(`     Read your prices from: ${pricingUrl}`);
  lines.push('');
  lines.push('     Why these six fields:');
  for (const axis of AXES) lines.push(`       ${axis.name} — ${axis.why}`);
  lines.push('-->');
  lines.push('<script type="application/ld+json">');
  lines.push(JSON.stringify(block, null, 2));
  lines.push('</script>');

  return {
    name: 'fit.html',
    purpose: `Paste into <head> on ${domain}. States price, audience and limits as facts an assistant can match a question against.`,
    language: 'html',
    content: lines.join('\n') + '\n',
    addresses: ['pricing_structured', 'jsonld_present'],
    incomplete: facts.pages.length === 0,
  };
}
