/**
 * The JSON-LD block, populated from observed data.
 *
 * Every value in here came out of the scan: the organisation name and
 * description from the page's own title and meta description, the URLs from
 * pages we confirmed, the FAQ entries from headings we actually saw. Where we
 * have no fact, the field carries a placeholder in angle brackets rather than a
 * plausible guess, because a JSON-LD block full of invented prices is worse
 * than no block at all — it is wrong in a machine-readable way.
 */

import type { FixFile, ScanFacts } from './index';
import { brandFrom, oneLine, pathOf } from './shared';

export function buildJsonLd(domain: string, facts: ScanFacts): FixFile {
  const origin = `https://${domain}`;
  const graph: Array<Record<string, unknown>> = [];

  // ---------------------------------------------------------------- who

  const organisation: Record<string, unknown> = {
    '@type': 'Organization',
    '@id': `${origin}/#organization`,
    name: brandFrom(facts.siteTitle, domain),
    url: origin,
  };
  if (facts.siteDescription) organisation.description = oneLine(facts.siteDescription);
  graph.push(organisation);

  // ---------------------------------------------------------------- what

  const website: Record<string, unknown> = {
    '@type': 'WebSite',
    '@id': `${origin}/#website`,
    url: origin,
    name: brandFrom(facts.siteTitle, domain),
    publisher: { '@id': `${origin}/#organization` },
  };
  graph.push(website);

  // ---------------------------------------------------------------- what it costs

  const pricingPage = facts.pages.find((page) => /\/pricing/i.test(page.url));

  if (facts.offerNodes === 0) {
    // The scan found prices on the page and no Offer node describing them, or
    // no prices at all. Either way the shape goes in with the numbers left as
    // placeholders: we read "$99" off a page, but not what it buys or whether
    // it is per seat, per month, or crossed out.
    const product: Record<string, unknown> = {
      '@type': 'Product',
      '@id': `${origin}/#product`,
      name: '<the name of the thing you sell>',
      brand: { '@id': `${origin}/#organization` },
      ...(pricingPage ? { url: pricingPage.url } : {}),
      offers: {
        '@type': 'Offer',
        '@comment':
          'We read prices off your page as text but will not guess which number is the price, what it buys, or whether it recurs. Fill these in.',
        price: '<0.00>',
        priceCurrency: '<USD>',
        availability: 'https://schema.org/InStock',
        url: pricingPage?.url ?? `${origin}/pricing`,
      },
    };
    graph.push(product);
  }

  // ---------------------------------------------------------------- where

  const pages = facts.pages.filter((page) => pathOf(page.url) !== '/');
  if (pages.length > 0) {
    graph.push({
      '@type': 'BreadcrumbList',
      '@id': `${origin}/#breadcrumbs`,
      itemListElement: pages.map((page, index) => ({
        '@type': 'ListItem',
        position: index + 1,
        name: page.title || pathOf(page.url),
        item: page.url,
      })),
    });
  }

  const block = {
    '@context': 'https://schema.org',
    '@graph': graph,
  };

  const lines: string[] = [];
  lines.push('<!-- JSON-LD for ' + domain);
  lines.push('     Generated by botready.dev. Every value below came out of your own pages.');
  lines.push('');
  lines.push('     Anything in <angle brackets> is a fact this scan could not read and');
  lines.push('     will not invent. Fill those in before you ship it: a block with a');
  lines.push('     guessed price is worse than no block, because it is wrong in a form');
  lines.push('     a machine will believe.');
  if (facts.jsonLdTypes.length > 0) {
    lines.push('');
    lines.push(`     Your page already carries: ${facts.jsonLdTypes.join(', ')}.`);
    lines.push('     Merge rather than replace, and keep one @id per thing.');
  }
  lines.push('-->');
  lines.push('<script type="application/ld+json">');
  lines.push(JSON.stringify(block, null, 2));
  lines.push('</script>');

  return {
    name: 'jsonld.html',
    purpose: `Paste into <head> on ${domain}. Describes who you are and what you sell in a form a machine reads without guessing.`,
    language: 'html',
    content: lines.join('\n') + '\n',
    addresses: ['jsonld_present', 'pricing_structured'],
    // Every field we could fill is filled; the placeholders are the point.
    incomplete: facts.pages.length === 0,
  };
}

