/**
 * The `<link rel="alternate" type="text/markdown">` tags, for the top 20 URLs.
 *
 * "Top" here means: the pages the scan confirmed first, then the sitemap's own
 * order, which is the order the site itself chose. Twenty because that is the
 * number a person will actually paste, and because past twenty this stops being
 * a copy-and-paste job and starts being a template change.
 *
 * The file also carries the Link header form and the server-side note, because
 * a tag on the page is the weakest of the three: it only helps a client that
 * already downloaded the HTML it was trying to avoid.
 */

import type { FixFile, ScanFacts } from './index';

const MAX_URLS = 20;

export function buildMarkdownAlternates(domain: string, facts: ScanFacts): FixFile {
  const urls = pickUrls(facts);

  const lines: string[] = [];

  lines.push(`<!-- Markdown alternates for ${domain}`);
  lines.push('     Generated by botready.dev from a scan of your sitemap and pages.');
  lines.push('');
  lines.push('     Three ways to advertise the same thing, weakest first:');
  lines.push('');
  lines.push('     1. The link tag below. A client has to download your HTML to find it,');
  lines.push('        which is the download it was hoping to skip.');
  lines.push('     2. The Link header, further down. A client sees it on a HEAD request,');
  lines.push('        so it can decide before paying for the body.');
  lines.push('     3. Content negotiation on Accept: text/markdown, which is the one that');
  lines.push('        needs no second URL at all. Also further down.');
  lines.push('');
  lines.push('     Doing 1 is worth doing. Doing 3 is worth more. -->');
  lines.push('');

  if (urls.length === 0) {
    lines.push('<!-- This scan found no URLs to generate tags for: your sitemap was not');
    lines.push('     readable and we only confirmed the page we were pointed at. Publish a');
    lines.push('     sitemap and re-run the scan, and this file will fill in. -->');
    return file(domain, lines, true);
  }

  lines.push('<!-- 1. Per page, in <head>. Each tag goes on the page it describes. -->');
  lines.push('');
  for (const url of urls) {
    const markdown = markdownUrlFor(url);
    lines.push(`<!-- on ${url} -->`);
    lines.push(`<link rel="alternate" type="text/markdown" href="${markdown}">`);
  }
  lines.push('');
  lines.push('<!-- 2. The same thing as a response header, which a HEAD request sees.');
  lines.push('');
  const first = urls[0];
  if (first) {
    lines.push(`     Link: <${markdownUrlFor(first)}>; rel="alternate"; type="text/markdown"`);
  }
  lines.push('');
  lines.push('     3. Content negotiation. When a request carries');
  lines.push('');
  lines.push('     Accept: text/markdown');
  lines.push('');
  lines.push('     answer with the markdown at the same URL and');
  lines.push('');
  lines.push('     Content-Type: text/markdown; charset=utf-8');
  lines.push('     Vary: Accept');
  lines.push('');
  lines.push('     The Vary header is not optional: without it a cache will serve your');
  lines.push('     markdown to a browser and your HTML to an agent, at random. -->');

  return file(domain, lines, false);
}

/**
 * Confirmed pages first, because those are the ones we know return 200, then
 * the sitemap's own order. Deduplicated on the path.
 */
function pickUrls(facts: ScanFacts): string[] {
  const seen = new Set<string>();
  const out: string[] = [];

  const push = (url: string) => {
    let key: string;
    try {
      const parsed = new URL(url);
      key = `${parsed.origin}${parsed.pathname.replace(/\/$/, '')}`;
    } catch {
      return;
    }
    if (seen.has(key)) return;
    seen.add(key);
    out.push(url);
  };

  for (const page of facts.pages) push(page.url);
  for (const entry of facts.sitemap.urls) push(entry.loc);

  return out.slice(0, MAX_URLS);
}

/**
 * `https://example.com/pricing` -> `https://example.com/pricing.md`
 *
 * A suggestion rather than a claim: we do not know what your markdown URLs will
 * be, and the comment in the file says so. The `.md` suffix is the convention
 * with the most adoption right now.
 */
function markdownUrlFor(url: string): string {
  try {
    const parsed = new URL(url);
    const path = parsed.pathname.replace(/\/$/, '');
    parsed.pathname = path === '' ? '/index.md' : `${path}.md`;
    parsed.search = '';
    parsed.hash = '';
    return parsed.toString();
  } catch {
    return `${url.replace(/\/$/, '')}.md`;
  }
}

function file(domain: string, lines: string[], incomplete: boolean): FixFile {
  return {
    name: 'markdown-alternates.html',
    purpose: `The link tags, the Link header and the content negotiation note for the top ${MAX_URLS} URLs on ${domain}.`,
    language: 'html',
    content: lines.join('\n').trimEnd() + '\n',
    addresses: ['markdown_alternate', 'content_negotiation'],
    incomplete,
  };
}
