/**
 * The corrected robots.txt block.
 *
 * It names the agents this scan found refused, and nothing else. A generic
 * "here is a good robots.txt" is something anyone can write; the value is that
 * this one lists the four user agent tokens that answered 403 on your edge
 * twenty seconds ago.
 *
 * Two refusals with two different remedies, and the file says which is which,
 * because pasting an Allow line into robots.txt does not turn off a WAF rule:
 *
 *   refused by robots.txt   these lines fix it
 *   refused by the edge     these lines do not, and the file says so
 */

import { catalog } from '../catalog';

import type { FixFile, ScanFacts } from './index';

export function buildRobotsBlock(domain: string, facts: ScanFacts): FixFile {
  const lines: string[] = [];
  const byId = new Map(catalog.agents.map((a) => [a.id, a]));

  const robotsRefused = facts.refusedByRobots
    .map((id) => byId.get(id))
    .filter((a): a is NonNullable<typeof a> => Boolean(a));

  const edgeRefused = facts.refusedByEdge
    .map((r) => ({ ...r, agent: byId.get(r.id) }))
    .filter((r): r is typeof r & { agent: NonNullable<typeof r.agent> } => Boolean(r.agent));

  lines.push(`# robots.txt for ${domain}`);
  lines.push(`# Generated by botready.dev from a scan of https://${domain}/`);
  lines.push('#');

  if (robotsRefused.length === 0 && edgeRefused.length === 0) {
    lines.push('# This scan found no reading agent refused, by robots.txt or at the edge.');
    lines.push('# The block below is what you already have, written out, so you have a');
    lines.push('# baseline to diff against the next time something changes.');
    lines.push('');
    lines.push(...allowAll());
    return file(domain, lines, false);
  }

  if (robotsRefused.length > 0) {
    lines.push(`# Your robots.txt currently disallows ${robotsRefused.length} reading`);
    lines.push(`# ${robotsRefused.length === 1 ? 'agent' : 'agents'}:`);
    for (const agent of robotsRefused) lines.push(`#   ${tokenFor(agent.ua)}`);
    if (facts.searchCrawlersAllowed) {
      lines.push('#');
      lines.push('# Googlebot and Bingbot are not disallowed, which is the shape of the');
      lines.push('# mistake rather than of a decision. Replacing the rules below with');
      lines.push('# these lines lets them read what search already reads.');
    }
    lines.push('');
    lines.push(...allowAll());
    lines.push('');
    for (const agent of robotsRefused) {
      lines.push(`User-agent: ${tokenFor(agent.ua)}`);
      lines.push('Allow: /');
      lines.push('');
    }
  } else {
    lines.push('# Nothing in your robots.txt refuses a reading agent. This block is what');
    lines.push('# you already have, written out, so you have a baseline to diff against.');
    lines.push('');
    lines.push(...allowAll());
    lines.push('');
  }

  if (edgeRefused.length > 0) {
    lines.push('# ----------------------------------------------------------------');
    lines.push('#');
    lines.push('# These lines will not fix the following, and it is worth being clear');
    lines.push('# about why. During this scan your edge answered these clients with a');
    lines.push('# status your robots.txt does not ask for:');
    lines.push('#');
    for (const refusal of edgeRefused) {
      const detail = [
        refusal.server ? `server: ${refusal.server}` : '',
        refusal.cfMitigated ? `cf-mitigated: ${refusal.cfMitigated}` : '',
      ]
        .filter(Boolean)
        .join(', ');
      lines.push(
        `#   ${tokenFor(refusal.agent.ua).padEnd(18)} HTTP ${refusal.status}${detail ? `   (${detail})` : ''}`,
      );
    }
    lines.push('#');
    lines.push('# robots.txt is a request and a WAF rule is an enforcement, so the fix is');
    lines.push('# in whatever is in front of your application, not in this file:');
    lines.push('#');
    if (edgeRefused.some((r) => r.cfMitigated)) {
      lines.push('#   Cloudflare  Security > Bots, and the WAF custom rules. The');
      lines.push('#               cf-mitigated header above means a rule matched, so');
      lines.push('#               there is a specific rule to find rather than a setting');
      lines.push('#               to guess at. Add a skip rule for these user agents.');
    } else {
      lines.push('#   Look for a bot-protection or rate-limiting rule matching on user');
      lines.push('#   agent, and add an exception for these tokens.');
    }
    lines.push('#');
    lines.push('# Verify by re-running the scan rather than by reading the config. The');
    lines.push('# only proof that a client can read your site is that it did.');
  }

  return file(domain, lines, false);
}

function allowAll(): string[] {
  return ['User-agent: *', 'Allow: /'];
}

/**
 * The token a publisher writes in robots.txt, which is the product token from
 * the user agent string: `ClaudeBot/1.0` addresses as `ClaudeBot`.
 */
function tokenFor(userAgent: string): string {
  return (userAgent.split('/')[0] ?? userAgent).trim();
}

function file(domain: string, lines: string[], incomplete: boolean): FixFile {
  return {
    name: 'robots.txt',
    purpose: `Merge this into https://${domain}/robots.txt. It names the agents this scan found refused and separates the ones this file can fix from the ones it cannot.`,
    language: 'text',
    content: lines.join('\n').trimEnd() + '\n',
    addresses: ['robots_agent_rules', 'agent_status_parity'],
    incomplete,
  };
}
