/**
 * waf-rule.txt: the one rule that lets declared AI agents past a managed
 * challenge.
 *
 * Written only for the agents the scan saw refused at the edge, named by the
 * user-agent token the catalog requests as. When the edge answered with
 * `cf-mitigated: challenge` the rule is phrased as a Cloudflare expression,
 * because that header is Cloudflare's; otherwise it is a generic allowlist
 * note that any WAF can be configured from.
 */

import { catalog } from '../catalog';

import type { FixFile, ScanFacts } from './index';

export function buildWafRule(domain: string, facts: ScanFacts): FixFile {
  const byId = new Map(catalog.agents.map((a) => [a.id, a]));
  const refused = facts.refusedByEdge
    .map((r) => ({ ...r, agent: byId.get(r.id) }))
    .filter((r): r is typeof r & { agent: NonNullable<typeof r.agent> } => Boolean(r.agent));

  const lines: string[] = [`# WAF rule for ${domain}`, '# Generated by botready.dev from the scan of this domain.', ''];

  if (refused.length === 0) {
    lines.push(
      '# The scan saw no agent refused at the edge: every declared client got the',
      '# same status class as the Chrome control. There is nothing to allow.',
      '# Keep this file as the rule to reach for if a managed ruleset changes',
      '# under you; the agents below are the ones we request as.',
      '',
      ...catalog.agents.filter((a) => a.role === 'agent').map((a) => `#   ${token(a.ua)}`),
      '',
    );
    return {
      name: 'waf-rule.txt',
      purpose: 'The allow rule for declared AI agents, ready for the day a firewall rule changes.',
      language: 'text',
      content: lines.join('\n'),
      addresses: ['agent_status_parity'],
      incomplete: true,
    };
  }

  const cloudflare = refused.some((r) => r.cfMitigated || /cloudflare/i.test(r.server));
  const tokens = refused.map((r) => token(r.agent.ua));

  lines.push(
    `# These clients were refused with ${[...new Set(refused.map((r) => r.status))].join(', ')} from the same URL that`,
    '# returned 200 to Chrome, in the same second:',
    ...refused.map((r) => `#   ${token(r.agent.ua)}  ->  ${r.status}${r.cfMitigated ? ` (cf-mitigated: ${r.cfMitigated})` : ''}${r.server ? ` server: ${r.server}` : ''}`),
    '',
  );

  if (cloudflare) {
    lines.push(
      '# Cloudflare: Security -> WAF -> Custom rules -> Create rule',
      '# Action: Skip -> "All remaining custom rules" and "Managed challenge"',
      '# Expression:',
      tokens.map((t) => `(http.user_agent contains "${t}")`).join('\nor '),
      '',
      '# Place it above the managed ruleset so it is evaluated first. Nothing else',
      '# about your bot protection changes: only requests carrying one of these',
      '# exact user-agent tokens skip the challenge.',
    );
  } else {
    lines.push(
      '# Allow requests whose User-Agent header contains any of these tokens to',
      '# skip the bot challenge. Every major WAF has an equivalent of this rule;',
      '# the expression below is written in the common "contains" form.',
      tokens.map((t) => `user_agent contains "${t}"`).join('\nOR '),
    );
  }

  lines.push('', '# Re-run the check afterwards: https://botready.dev', '');

  return {
    name: 'waf-rule.txt',
    purpose: 'The one firewall rule that lets the refused agents through, written for the edge the scan saw.',
    language: 'text',
    content: lines.join('\n'),
    addresses: ['agent_status_parity'],
    incomplete: false,
  };
}

/** The product token of a user agent: "ClaudeBot/1.0" -> "ClaudeBot". */
function token(ua: string): string {
  const match = ua.match(/([A-Za-z][A-Za-z0-9-]*Bot|Google-Extended|[A-Za-z][A-Za-z0-9-]*)\/?/);
  return match?.[1] ?? ua.split('/')[0] ?? ua;
}
